version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14  # Specify the Node.js version for NestJS
    
  pre_build:
    commands:
      - echo Authenticating with Amazon ECR...
      - aws ecr get-login-password --region $ECR_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY_URI

  build:
    commands:
      - echo "ECR_REGISTRY_URI is $ECR_REGISTRY_URI"
      - echo "ECR_REGION is $ECR_REGION"
      - echo Installing Node.js dependencies...
      - npm install
      - echo Building the NestJS application...
      - npm run build
      - echo Building the Docker image...
      - docker build -t boilerplate-backend .

  post_build:
    commands:
      - echo Tagging the Docker image...
      - docker tag boilerplate-backend:latest 851725420958.dkr.ecr.us-east-2.amazonaws.com/boilerplate-backend:latest
      - echo Pushing the Docker image to ECR...
      - docker push 851725420958.dkr.ecr.us-east-2.amazonaws.com/boilerplate-backend:latest
      - aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --region us-east-2 --force-new-deployment

# artifacts:
#   files: imagedefinitions.json

# cache:
#   paths:
#     - '/root/.docker/cli-plugins'
#     - '/root/.npm/**/*'
#     - 'dist/**/*'

